version: '3.9'

services:
  doctor-service:
    build: .
    container_name: doctor-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/doctor_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass

  db:
    image: mysql:8.1
    container_name: doctor-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 25052005
      MYSQL_DATABASE: doctor_service
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
